query Pokemons($offset: Int, $search: String, $isFavorite: Boolean, $type: String){
  pokemons(query: { limit: 12, search: $search, offset: $offset, filter: { isFavorite: $isFavorite, type: $type } }) {
    edges {
      id
      name
      types
      image
      isFavorite
    }
  }
}